// <auto-generated />
using System;
using AMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Migrations
{
    [DbContext(typeof(AMSDbContext))]
    [Migration("20251118074131_hi2")]
    partial class hi2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AMS.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            FullName = "Quản Trị Viên",
                            LastLogin = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2b$12$Dvin/fmQwvI7yF8PVrC//uRlbRmkTCzsFG1xO7xGOcG/N2QBITIqS",
                            PhoneNumber = "0123456789",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AMS.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Plate");

                    b.HasIndex("RoomId", "Plate")
                        .IsUnique();

                    b.ToTable("Bikes", (string)null);
                });

            modelBuilder.Entity("AMS.Models.Contract", b =>
                {
                    b.Property<string>("ContractId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AddendumNotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DepositReturnDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DueDay")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LateFeePolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBikeAllowance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOccupants")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeedsAddendum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PaymentMethods")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SecurityDeposit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TenantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ContractId");

                    b.HasIndex("ContractNumber");

                    b.HasIndex("RoomCode");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("AMS.Models.ContractAddendum", b =>
                {
                    b.Property<string>("AddendumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddendumNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewTenantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldTenantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentContractId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AddendumId");

                    b.HasIndex("AddendumNumber");

                    b.HasIndex("ParentContractId");

                    b.ToTable("ContractAddendums");
                });

            modelBuilder.Entity("AMS.Models.FeeInstance", b =>
                {
                    b.Property<string>("FeeInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeeTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(1m);

                    b.Property<decimal>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("RoomChargeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FeeInstanceId");

                    b.HasIndex("RoomChargeId");

                    b.ToTable("FeeInstances", t =>
                        {
                            t.HasCheckConstraint("CK_FeeInstance_NonNegative", "[Rate] >= 0 AND [Quantity] >= 0");
                        });
                });

            modelBuilder.Entity("AMS.Models.FeeType", b =>
                {
                    b.Property<string>("FeeTypeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("ApplyAllRooms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("DefaultRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitLabel")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("FeeTypeId");

                    b.HasIndex("Name");

                    b.ToTable("FeeTypes");
                });

            modelBuilder.Entity("AMS.Models.House", b =>
                {
                    b.Property<int>("IdHouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdHouse");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("AMS.Models.PaymentCycle", b =>
                {
                    b.Property<string>("CycleId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Closed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("CycleId");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("PaymentCycles");
                });

            modelBuilder.Entity("AMS.Models.PaymentRecord", b =>
                {
                    b.Property<string>("PaymentRecordId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsPartial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RoomChargeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentRecordId");

                    b.HasIndex("RoomChargeId");

                    b.ToTable("PaymentRecords", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentRecord_Amount_Positive", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("AMS.Models.Room", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("BikeExtraFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(100000m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EmergencyContactRoomOccupancyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreeBikeAllowance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("HouseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HouseIdHouse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBikeAllowance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("MaxOccupants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdRoom");

                    b.HasIndex("EmergencyContactRoomOccupancyId");

                    b.HasIndex("HouseIdHouse");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.HasIndex("HouseID", "RoomCode")
                        .IsUnique();

                    b.ToTable("Rooms", t =>
                        {
                            t.HasCheckConstraint("CK_Room_Area_Positive", "[Area] > 0");

                            t.HasCheckConstraint("CK_Room_FreeBikeAllowance_NonNegative", "[FreeBikeAllowance] >= 0");

                            t.HasCheckConstraint("CK_Room_FreeBikeAllowance_Within_Max", "([MaxBikeAllowance] = 0 OR [FreeBikeAllowance] <= [MaxBikeAllowance])");

                            t.HasCheckConstraint("CK_Room_MaxBikeAllowance_NonNegative", "[MaxBikeAllowance] >= 0");

                            t.HasCheckConstraint("CK_Room_MaxOccupants_Positive", "[MaxOccupants] >= 1");

                            t.HasCheckConstraint("CK_Room_Price_NonNegative", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("AMS.Models.RoomCharge", b =>
                {
                    b.Property<string>("RoomChargeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BaseRent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CustomFeesTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("CycleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ElectricAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("FirstSentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal>("UtilityFeesTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("WaterAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("RoomChargeId");

                    b.HasIndex("CycleId", "RoomCode")
                        .IsUnique();

                    b.ToTable("RoomCharges", t =>
                        {
                            t.HasCheckConstraint("CK_RoomCharge_Amounts_NonNegative", "[UtilityFeesTotal] >= 0 AND [CustomFeesTotal] >= 0 AND [ElectricAmount] >= 0 AND [WaterAmount] >= 0 AND [AmountPaid] >= 0");

                            t.HasCheckConstraint("CK_RoomCharge_BaseRent_NonNegative", "[BaseRent] >= 0");
                        });
                });

            modelBuilder.Entity("AMS.Models.RoomOccupancy", b =>
                {
                    b.Property<int>("IdRoomOccupancy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal>("DepositContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("MoveInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MoveOutDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRoomOccupancy");

                    b.HasIndex("RoomId", "MoveOutDate");

                    b.HasIndex("TenantId", "MoveOutDate");

                    b.ToTable("RoomOccupancies");
                });

            modelBuilder.Entity("AMS.Models.Tenant", b =>
                {
                    b.Property<int>("IdTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("MoveInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MoveOutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTenant");

                    b.HasIndex("FullName");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("RoomId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("AMS.Models.Bike", b =>
                {
                    b.HasOne("AMS.Models.Tenant", "OwnerTenant")
                        .WithMany("Bikes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerTenant");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AMS.Models.ContractAddendum", b =>
                {
                    b.HasOne("AMS.Models.Contract", "Parent")
                        .WithMany("Addendums")
                        .HasForeignKey("ParentContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AMS.Models.FeeInstance", b =>
                {
                    b.HasOne("AMS.Models.RoomCharge", null)
                        .WithMany("Fees")
                        .HasForeignKey("RoomChargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS.Models.PaymentRecord", b =>
                {
                    b.HasOne("AMS.Models.RoomCharge", null)
                        .WithMany("Payments")
                        .HasForeignKey("RoomChargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS.Models.Room", b =>
                {
                    b.HasOne("AMS.Models.RoomOccupancy", null)
                        .WithMany()
                        .HasForeignKey("EmergencyContactRoomOccupancyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AMS.Models.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMS.Models.House", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HouseIdHouse");

                    b.Navigation("House");
                });

            modelBuilder.Entity("AMS.Models.RoomCharge", b =>
                {
                    b.HasOne("AMS.Models.PaymentCycle", null)
                        .WithMany("RoomCharges")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AMS.Models.ElectricReading", "ElectricReading", b1 =>
                        {
                            b1.Property<string>("RoomChargeId1")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Confirmed")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false)
                                .HasColumnName("ElectricConfirmed");

                            b1.Property<int>("Current")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ElectricCur");

                            b1.Property<int>("Previous")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ElectricPrev");

                            b1.Property<decimal>("Rate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("ElectricRate");

                            b1.HasKey("RoomChargeId1");

                            b1.ToTable("RoomCharges");

                            b1.WithOwner()
                                .HasForeignKey("RoomChargeId1");
                        });

                    b.OwnsOne("AMS.Models.WaterReading", "WaterReading", b1 =>
                        {
                            b1.Property<string>("RoomChargeId1")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Confirmed")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false)
                                .HasColumnName("WaterConfirmed");

                            b1.Property<int>("Current")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WaterCur");

                            b1.Property<int>("Previous")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WaterPrev");

                            b1.Property<decimal>("Rate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("WaterRate");

                            b1.HasKey("RoomChargeId1");

                            b1.ToTable("RoomCharges");

                            b1.WithOwner()
                                .HasForeignKey("RoomChargeId1");
                        });

                    b.Navigation("ElectricReading");

                    b.Navigation("WaterReading");
                });

            modelBuilder.Entity("AMS.Models.RoomOccupancy", b =>
                {
                    b.HasOne("AMS.Models.Room", "Room")
                        .WithMany("RoomOccupancies")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMS.Models.Tenant", "Tenant")
                        .WithMany("RoomOccupancies")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AMS.Models.Tenant", b =>
                {
                    b.HasOne("AMS.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AMS.Models.Contract", b =>
                {
                    b.Navigation("Addendums");
                });

            modelBuilder.Entity("AMS.Models.House", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("AMS.Models.PaymentCycle", b =>
                {
                    b.Navigation("RoomCharges");
                });

            modelBuilder.Entity("AMS.Models.Room", b =>
                {
                    b.Navigation("RoomOccupancies");
                });

            modelBuilder.Entity("AMS.Models.RoomCharge", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("AMS.Models.Tenant", b =>
                {
                    b.Navigation("Bikes");

                    b.Navigation("RoomOccupancies");
                });
#pragma warning restore 612, 618
        }
    }
}
